{% set name = "optype" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/optype-{{ version }}.tar.gz
  sha256: 51c8dd104ac197457059bcee5e256160a641ca72c6c852012d952790a5e0cac0

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0


requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - typing-extensions >=4.10  # [py<313]

test:
  imports:
    - optype
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jorenham/optype
  summary: Building blocks for precise & flexible type hints
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucascolley
    - jorenham
